name: Build and Release FileCollector

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build for ${{ matrix.os-name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            os-name: Windows
            rid: win-x64
            artifact-name-suffix: win-x64
            output-archive-name: FileCollector-win-x64.zip
          - os: macos-latest
            os-name: macOS
            rid: osx-x64
            artifact-name-suffix: osx-x64
            output-archive-name: FileCollector-osx-x64.tar.gz
          - os: ubuntu-latest
            os-name: Linux
            rid: linux-x64
            artifact-name-suffix: linux-x64
            output-archive-name: FileCollector-linux-x64.tar.gz

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Determine Application Version Components
        id: version_components
        run: |
          [xml]$PropsDocument = Get-Content -Path ./Directory.Build.props
          $Major = $PropsDocument.Project.PropertyGroup.MyProductVersionMajor.InnerText
          $Minor = $PropsDocument.Project.PropertyGroup.MyProductVersionMinor.InnerText
          $Patch = "${{ github.run_number }}"
          $Revision = "${{ github.run_attempt }}"
          $AppVersion = "$Major.$Minor.$Patch.$Revision"
          echo "Full application version: $AppVersion"
          echo "app_version=$AppVersion" >> $env:GITHUB_OUTPUT
          echo "patch_version=$Patch" >> $env:GITHUB_OUTPUT
          echo "revision_version=$Revision" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Restore dependencies
        run: dotnet restore FileCollector/FileCollector.csproj

      - name: Publish application
        run: |
          echo "Publishing application with version components: Major.Minor (from props), Patch=${{ steps.version_components.outputs.patch_version }}, Revision=${{ steps.version_components.outputs.revision_version }}"
          dotnet publish FileCollector/FileCollector.csproj -c Release -r ${{ matrix.rid }} --self-contained true /p:PublishSingleFile=false /p:DebugType=None /p:PublishTrimmed=false /p:PublishReadyToRun=false /p:MyProductVersionPatch=${{ steps.version_components.outputs.patch_version }} /p:MyProductVersionRevision=${{ steps.version_components.outputs.revision_version }} -o ./publish_output
        shell: pwsh

      - name: List publish_output contents (Diagnostics)
        if: runner.os == 'Windows'
        run: Get-ChildItem -Path ./publish_output -Recurse | Select-Object FullName, Length, Mode, LastWriteTime
        shell: pwsh
      
      - name: List publish_output contents (Diagnostics)
        if: runner.os != 'Windows'
        run: ls -lR ./publish_output
        shell: bash

      - name: Archive output (Windows)
        if: matrix.os == 'windows-latest'
        run: Compress-Archive -Path ./publish_output/* -DestinationPath ./${{ matrix.output-archive-name }}
        shell: pwsh

      - name: Archive output (macOS/Linux)
        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
        run: tar -czvf ./${{ matrix.output-archive-name }} -C ./publish_output .
        shell: bash

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: FileCollector-${{ matrix.artifact-name-suffix }}
          path: ./${{ matrix.output-archive-name }}

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Checkout code # Needed to read Directory.Build.props
        uses: actions/checkout@v4

      - name: Generate Release Info
        id: release_info
        run: |
          # Using Python for robust XML parsing in bash environment
          # Ensure Python is available on the runner (ubuntu-latest usually has it)
          VERSION_INFO=$(python -c "
          import xml.etree.ElementTree as ET
          tree = ET.parse('./Directory.Build.props')
          root = tree.getroot()
          major = root.find('.//MyProductVersionMajor').text
          minor = root.find('.//MyProductVersionMinor').text
          patch = '${{ github.run_number }}'
          revision = '${{ github.run_attempt }}'
          app_version = f'{major}.{minor}.{patch}.{revision}'
          print(f'tag_name=v{app_version}')
          print(f'app_version_for_display={app_version}')
          print(f'release_name=Release v{app_version}')
          ")
          echo "$VERSION_INFO" >> $GITHUB_OUTPUT
        shell: bash

      - name: Download all build artifacts
        uses: actions/download-artifact@v4

      - name: List downloaded files (for verification)
        run: ls -R .
        shell: bash

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release_info.outputs.tag_name }}
          name: ${{ steps.release_info.outputs.release_name }}
          body: |
            Automated release for commit ${{ github.sha }}.
            Application version: ${{ steps.release_info.outputs.app_version_for_display }}
            Builds for Windows, macOS, and Linux are attached.
          draft: false
          prerelease: false
          files: |
            ./FileCollector-win-x64/FileCollector-win-x64.zip
            ./FileCollector-osx-x64/FileCollector-osx-x64.tar.gz
            ./FileCollector-linux-x64/FileCollector-linux-x64.tar.gz