name: Build and Release FileCollector

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build for ${{ matrix.os-name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            os-name: Windows
            rid: win-x64
            artifact-name-suffix: win-x64
            output-archive-name: FileCollector-win-x64.zip
          - os: macos-latest
            os-name: macOS
            rid: osx-x64
            artifact-name-suffix: osx-x64
            output-archive-name: FileCollector-osx-x64.tar.gz
          - os: ubuntu-latest
            os-name: Linux
            rid: linux-x64
            artifact-name-suffix: linux-x64
            output-archive-name: FileCollector-linux-x64.tar.gz

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore FileCollector/FileCollector.csproj

      - name: Publish application
        run: dotnet publish FileCollector/FileCollector.csproj -c Release -r ${{ matrix.rid }} --self-contained true /p:PublishSingleFile=true /p:DebugType=portable /p:PublishTrimmed=false -o ./publish_output

      - name: List publish_output contents (Diagnostics)
        if: runner.os == 'Windows'
        run: Get-ChildItem -Path ./publish_output -Recurse | Select-Object FullName, Length, Mode, LastWriteTime
        shell: pwsh
      
      - name: List publish_output contents (Diagnostics)
        if: runner.os != 'Windows'
        run: ls -lR ./publish_output
        shell: bash

      - name: Archive output (Windows)
        if: matrix.os == 'windows-latest'
        run: Compress-Archive -Path ./publish_output/* -DestinationPath ./${{ matrix.output-archive-name }}
        shell: pwsh

      - name: Archive output (macOS/Linux)
        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
        run: tar -czvf ./${{ matrix.output-archive-name }} -C ./publish_output .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: FileCollector-${{ matrix.artifact-name-suffix }}
          path: ./${{ matrix.output-archive-name }}

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Generate tag name
        id: tagger
        run: echo "tag_name=v${{ github.run_id }}.${{ github.run_attempt }}" >> $GITHUB_OUTPUT

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        # No 'name' is specified, so all artifacts from this workflow run are downloaded.
        # Each artifact will be in a subdirectory named after the artifact.

      - name: List downloaded files (for verification)
        run: ls -R .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tagger.outputs.tag_name }}
          name: Release ${{ steps.tagger.outputs.tag_name }}
          body: |
            Automated release for commit ${{ github.sha }}.
            Builds for Windows, macOS, and Linux are attached.
          draft: false
          prerelease: false
          files: |
            ./FileCollector-win-x64/FileCollector-win-x64.zip
            ./FileCollector-osx-x64/FileCollector-osx-x64.tar.gz
            ./FileCollector-linux-x64/FileCollector-linux-x64.tar.gz